export const HEARTBEAT_INTERVAL_MS = 4000;
export const DRIFT_THRESHOLD_S = 0.75;
export const SEEK_EPSILON_S = 0.35;
export const GUARD_SUPPRESS_WINDOW_MS = 400;
export const ROOM_CODE_LENGTH = 6;
export const ROOM_CODE_ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
